/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import forms.clan.FormRadSaClanovima;
import forms.potvrda.FormIzdavanje;
import forms.knjiga.FormRadSaKnjigama;
import forms.knjiga.FormKreirajKnjigu;
import forms.clan.FormKreiranjeClana;
import forms.potvrda.FormRadSaPotvrdama;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Stefan
 */
public class FormMaini extends javax.swing.JFrame {

    /**
     * Creates new form GlavniMeni
     */
    public FormMaini() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPozadina = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        meniBiblioteka = new javax.swing.JMenu();
        miIzdavanje = new javax.swing.JMenuItem();
        miVracanje = new javax.swing.JMenuItem();
        meniClanovi = new javax.swing.JMenu();
        miKreirajClana = new javax.swing.JMenuItem();
        miClanoviBiblioteke = new javax.swing.JMenuItem();
        meniKnjige = new javax.swing.JMenu();
        miKreirajKnjigu = new javax.swing.JMenuItem();
        miPrikaziKnjige = new javax.swing.JMenuItem();
        meniKorisnik = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteka Višnja");

        lblPozadina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPozadina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/BibliotekaVisnja.jpg"))); // NOI18N

        meniBiblioteka.setText("BIBLIOTEKA");
        meniBiblioteka.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N

        miIzdavanje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miIzdavanje.setText("Izdavanje knjiga");
        miIzdavanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIzdavanjeActionPerformed(evt);
            }
        });
        meniBiblioteka.add(miIzdavanje);

        miVracanje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miVracanje.setText("Vraćanje knjiga");
        miVracanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVracanjeActionPerformed(evt);
            }
        });
        meniBiblioteka.add(miVracanje);

        jMenuBar1.add(meniBiblioteka);

        meniClanovi.setText("ČLANOVI");
        meniClanovi.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N

        miKreirajClana.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miKreirajClana.setText("Kreiraj novog člana");
        miKreirajClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKreirajClanaActionPerformed(evt);
            }
        });
        meniClanovi.add(miKreirajClana);

        miClanoviBiblioteke.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miClanoviBiblioteke.setText("Članovi biblioteke");
        miClanoviBiblioteke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClanoviBibliotekeActionPerformed(evt);
            }
        });
        meniClanovi.add(miClanoviBiblioteke);

        jMenuBar1.add(meniClanovi);

        meniKnjige.setText("KNJIGE");
        meniKnjige.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N

        miKreirajKnjigu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miKreirajKnjigu.setText("Unesi novu knjigu");
        miKreirajKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKreirajKnjiguActionPerformed(evt);
            }
        });
        meniKnjige.add(miKreirajKnjigu);

        miPrikaziKnjige.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miPrikaziKnjige.setText("Prikaži knjige");
        miPrikaziKnjige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrikaziKnjigeActionPerformed(evt);
            }
        });
        meniKnjige.add(miPrikaziKnjige);

        jMenuBar1.add(meniKnjige);

        meniKorisnik.setText("KORISNIK");
        meniKorisnik.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N

        miLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        meniKorisnik.add(miLogout);

        jMenuBar1.add(meniKorisnik);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPozadina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPozadina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miIzdavanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIzdavanjeActionPerformed
        new FormIzdavanje(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_miIzdavanjeActionPerformed

    private void miVracanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVracanjeActionPerformed
        new FormRadSaPotvrdama(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_miVracanjeActionPerformed

    private void miKreirajClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajClanaActionPerformed
        new FormKreiranjeClana(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_miKreirajClanaActionPerformed

    private void miClanoviBibliotekeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClanoviBibliotekeActionPerformed
        new FormRadSaClanovima(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_miClanoviBibliotekeActionPerformed

    private void miKreirajKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajKnjiguActionPerformed
        new FormKreirajKnjigu(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_miKreirajKnjiguActionPerformed

    private void miPrikaziKnjigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrikaziKnjigeActionPerformed
        new FormRadSaKnjigama(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_miPrikaziKnjigeActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        
        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da se izlogujete?", "CONFIRMATION", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            new FormLogin().setVisible(true);
            this.dispose();
            
        }
    }//GEN-LAST:event_miLogoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblPozadina;
    private javax.swing.JMenu meniBiblioteka;
    private javax.swing.JMenu meniClanovi;
    private javax.swing.JMenu meniKnjige;
    private javax.swing.JMenu meniKorisnik;
    private javax.swing.JMenuItem miClanoviBiblioteke;
    private javax.swing.JMenuItem miIzdavanje;
    private javax.swing.JMenuItem miKreirajClana;
    private javax.swing.JMenuItem miKreirajKnjigu;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miPrikaziKnjige;
    private javax.swing.JMenuItem miVracanje;
    // End of variables declaration//GEN-END:variables
}
